version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: somewordpress
      POSTGRES_DB: wordpress
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynet
    ports:
      - "5432:5432"

  app:
    image: quay.io/florian_even/opensaas-backend
    container_name: backend
    env_file:
      - /Users/florian/Desktop/dev/triathlon/opensaas/rueil-malmaison-triathlon/app/.env.server
    networks:
      - mynet
    depends_on:
      - db
    ports:
      - "3001:3001"
  
  frontend:
    image: quay.io/florian_even/opensaas-frontend
    container_name: frontend
    networks:
      - mynet
    ports:
      - "3000:80"

networks:
  mynet:
    driver: bridge

volumes:
  pg_data:
    driver: local
